优化stringify函数：修复外层引号处理及增强DOM元素检查

diff --git a/.github/workflows/sync-to-gitlab.yml b/.github/workflows/sync-to-gitlab.yml
--- a/.github/workflows/sync-to-gitlab.yml
+++ b/.github/workflows/sync-to-gitlab.yml
@@ -19,7 +19,7 @@ jobs:
           echo "Error: secrets.TOKEN is not set. Exiting."
           exit 1
         fi
-        
+
     - name: Checkout code
       uses: actions/checkout@v4
       with:
@@ -32,5 +32,5 @@ jobs:
       run: |
         REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
         git remote add gitlab https://oauth2:${{secrets.TOKEN}}@${GIT_PROVIDER}/${OWNER}/${REPO}.git
-        git push --all gitlab || { echo "Failed to push branches"; exit 1; }
-        git push --tags gitlab || { echo "Failed to push tags"; exit 1; }
+        git push -f --all gitlab || { echo "Failed to push branches"; exit 1; }
+        git push -f --tags gitlab || { echo "Failed to push tags"; exit 1; }
